AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable

inherit_gem:
  foobara-rubocop-rules:
    - rules/*

Naming/FileName:
  inherit_mode:
    merge:
      - Exclude

# Results in a cleaner-reading #execute
# TODO: consider making universal in foobara-rubocop-rules
Style/AndOr:
  Enabled: false
